---
title: "Untitled"
author: "JG"
date: "2023-10-31"
output: html_document
---

Load libraries
```{r}
library(here)
library(tmap)
library(sf)
library(dplyr)
library(readr)
library(readxl)
library(janitor)

here::here()
```

Read in data
```{r}
# read global gender inequality data 
ggi_data <- read_excel(here("../", "wk4_data", "HDR21-22_Statistical_Annex_HDI_Trends_Table.xlsx"), skip=4) %>%
  clean_names()

# read spatial data of the world
world_map <- st_read(here("../", "wk4_data", "world_Countries_Generalized.shp")) %>%
  clean_names()
```
Extract and join relevant data from global inequality data to world_map data
```{r}
# We want 2010 and 2019 data, and to remove irrelevant rows
ggi_data_clean <- ggi_data %>%
  select("country", "x2010", "x2019")

# Join this data to world map data
world_map_merge <- left_join(world_map, ggi_data_clean, by = "country")

# Transform strings to numeric for 2010 and 2019 columns
world_map_merge <- world_map_merge %>%
  transform(., x2010 = as.numeric(x2010), x2019 = as.numeric(x2019))
  

# Calculate difference in inequality between 2010 and 2019

world_map_merge <- world_map_merge %>%
  mutate(diff_2010_2019 = (x2019 - x2010))
```

Map data to inspect
```{r}
qtm(world_map_merge, fill = "diff_2010_2019")
```

